### PR TITLE
Add why not to share your API key

### PR DESCRIPTION
**Pull request by RileyDatLord**
I know it's kinda useless but might as well say you can get banned for sharing your API key as it can risk in that user posting a server count that is not a true server count.

### CODE REVIEW

**Comment by Draem** [comment]
token you mean api key

**Comment by RileyDatLord** [comment]
Yes

**Comment by RONTheCookie** [comment]
c o m m o n  s e n s e

**Comment by RileyDatLord** [comment]
people sometimes don't have `c o m m o n s e n s e`

**Comment by jellz** [comment]
Someone that was able to code their own bot and add it to the bot list should have enough common sense to not share their API key. If they do for some reason share their API key and get the account banned on the list, that is their fault. If they wish they can message a Senior Moderator on Discord with info regarding the situation and hopefully get the punishment reverted.

**Pull request closed without merging**
